version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - PORT=3000
      - MONGO_URL=mongodb+srv://perwatch-api:111967sami@case.zjtikvl.mongodb.net/
    depends_on:
      - mongo

volumes:
  mongo-data:
